Repository SOPT-29th-Joint-Seminar-6/Seminar_6_Android, pull requests merged in 2021-11, with the labels that each got.

#3 Feature/1 initial setting
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
Labels: suhyeon, Done

#4 Feature/2 transition logic
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/seminar_6_android/MainActivity.kt
  app/src/main/java/org/sopt/seminar_6_android/adapter/MainViewPagerAdapter.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/MainActivity.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/find/FindFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/kakaotv/KakaoTVFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/view/EmptyFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/view/TabMyViewFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/view/TabViewFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/view/ViewFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/view/adapter/TopViewPagerAdapter.kt
  app/src/main/res/color/selector_bottom_navi.xml
  app/src/main/res/drawable-hdpi/ic_tap_person.png
  app/src/main/res/drawable-mdpi/ic_tap_person.png
  app/src/main/res/drawable-xhdpi/ic_tap_person.png
  app/src/main/res/drawable-xxhdpi/ic_tap_person.png
  app/src/main/res/drawable-xxxhdpi/ic_tap_person.png
  app/src/main/res/drawable/ic_chatting.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/ic_store.xml
  app/src/main/res/drawable/ic_view.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_empty.xml
  app/src/main/res/layout/fragment_find.xml
  app/src/main/res/layout/fragment_kakao_t_v.xml
  app/src/main/res/layout/fragment_tab_view.xml
  app/src/main/res/layout/fragment_view.xml
  app/src/main/res/menu/menu_bottom_navi.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: suhyeon, Done

#7 UI/6 find news item
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/seminar_6_android/ui/find/FindFragment.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/find/NewsCardAdapter.kt
  app/src/main/java/org/sopt/seminar_6_android/ui/find/NewsData.kt
  app/src/main/res/drawable-hdpi/frame_43.png
  app/src/main/res/drawable-hdpi/ic_heart.png
  app/src/main/res/drawable-hdpi/ic_movie.png
  app/src/main/res/drawable-hdpi/ic_share.png
  app/src/main/res/drawable-hdpi/ic_web.png
  app/src/main/res/drawable-hdpi/img_movie_1.png
  app/src/main/res/drawable-hdpi/img_movie_2.png
  app/src/main/res/drawable-mdpi/frame_43.png
  app/src/main/res/drawable-mdpi/ic_heart.png
  app/src/main/res/drawable-mdpi/ic_movie.png
  app/src/main/res/drawable-mdpi/ic_share.png
  app/src/main/res/drawable-mdpi/ic_web.png
  app/src/main/res/drawable-mdpi/img_movie_1.png
  app/src/main/res/drawable-mdpi/img_movie_2.png
  app/src/main/res/drawable-xhdpi/frame_43.png
  app/src/main/res/drawable-xhdpi/ic_heart.png
  app/src/main/res/drawable-xhdpi/ic_movie.png
  app/src/main/res/drawable-xhdpi/ic_share.png
  app/src/main/res/drawable-xhdpi/ic_web.png
  app/src/main/res/drawable-xhdpi/img_movie_1.png
  app/src/main/res/drawable-xhdpi/img_movie_2.png
  app/src/main/res/drawable-xxhdpi/frame_43.png
  app/src/main/res/drawable-xxhdpi/ic_heart.png
  app/src/main/res/drawable-xxhdpi/ic_movie.png
  app/src/main/res/drawable-xxhdpi/ic_share.png
  app/src/main/res/drawable-xxhdpi/ic_web.png
  app/src/main/res/drawable-xxhdpi/img_movie_1.png
  app/src/main/res/drawable-xxhdpi/img_movie_2.png
  app/src/main/res/drawable-xxxhdpi/frame_43.png
  app/src/main/res/drawable-xxxhdpi/ic_heart.png
  app/src/main/res/drawable-xxxhdpi/ic_movie.png
  app/src/main/res/drawable-xxxhdpi/ic_share.png
  app/src/main/res/drawable-xxxhdpi/ic_web.png
  app/src/main/res/drawable-xxxhdpi/img_movie_1.png
  app/src/main/res/drawable-xxxhdpi/img_movie_2.png
  app/src/main/res/drawable/ic_channel.xml
  app/src/main/res/layout/find_news_card.xml
  app/src/main/res/layout/fragment_find.xml
  app/src/main/res/layout/item_find_news_list.xml
Labels: Done, chaeyoung

#11 Feature/2 transition logic
  .idea/misc.xml
  app/src/main/res/drawable-hdpi/ic_music.png
  app/src/main/res/drawable-mdpi/ic_music.png
  app/src/main/res/drawable-xhdpi/ic_music.png
  app/src/main/res/drawable-xxhdpi/ic_music.png
  app/src/main/res/drawable-xxxhdpi/ic_music.png
  app/src/main/res/drawable/ic_chatting_x_.xml
  app/src/main/res/layout/fragment_view.xml
  app/src/main/res/menu/menu_bottom_navi.xml
Labels: suhyeon
